name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Add remote origin
        run: git remote add heroku https://git.heroku.com/my-brand-website.git

      - name: Deploy backend to heroku
        run: git push --force heroku `git subtree split --prefix server HEAD`:master
